# Generated by Django 6.0.2 on 2026-03-01 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bf_l1_p1', models.BooleanField(default=False)),
                ('bf_l1_p2', models.BooleanField(default=False)),
                ('bf_l1_p3', models.BooleanField(default=False)),
                ('bf_l2_p1', models.BooleanField(default=False)),
                ('bf_l2_p2', models.BooleanField(default=False)),
                ('bf_l2_p3', models.BooleanField(default=False)),
                ('bf_l3_p1', models.BooleanField(default=False)),
                ('bf_l3_p2', models.BooleanField(default=False)),
                ('bf_l3_p3', models.BooleanField(default=False)),
                ('sqli_l1_p1', models.BooleanField(default=False)),
                ('sqli_l1_p2', models.BooleanField(default=False)),
                ('sqli_l1_p3', models.BooleanField(default=False)),
                ('sqli_l2_p1', models.BooleanField(default=False)),
                ('sqli_l2_p2', models.BooleanField(default=False)),
                ('sqli_l2_p3', models.BooleanField(default=False)),
                ('sqli_l3_p1', models.BooleanField(default=False)),
                ('sqli_l3_p2', models.BooleanField(default=False)),
                ('sqli_l3_p3', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
